#group:
#  group_name: <group_name>
#  component_name: <component_name>
#  buttons: [[button_name1,function_name1,parameter_name2,
#    [button_name2,function_name2,parameter_name2]]

group1:
  group_name: arm settings
  component_name: arm
  buttons: [[stop,trigger,stop],
    [init,trigger,init],
    [recover,trigger,recover]]

group2:
  group_name: arm pos
  component_name: arm
  buttons: [[stop,trigger,stop],
    [home,move,home],
    [folded,move,folded],
    [wave_left,move,wave_left],
    [wave_right,move,wave_right]]

# trajectories
   
group3:
  group_name: arm traj
  component_name: arm
  buttons: [[stop,trigger,stop],
    [wave,move,wave_left-wave_right-home]]




